services:
    updater:
        build:
            context: ../..
            dockerfile: setup/balances/updater.Dockerfile
        volumes:
            - spiral-databases:/spiral-databases

    worker:
        build:
            context: ../..
            dockerfile: setup/balances/worker.Dockerfile
        expose:
            - 8089
            - 9089
        volumes:
            - spiral-databases:/spiral-databases:ro

    proxy:
        build:
            context: ../..
            dockerfile: setup/balances/proxy.Dockerfile
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        volumes:
            - caddy_data:/data
            - spiral-databases:/spiral-databases:ro

volumes:
    spiral-databases:
        external: true
    caddy_data:
        external: true
