# This is a basic workflow to help you get started with Actions

name: Build WebClient

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # allow manual run
  workflow_dispatch:

jobs:
  client-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # setup wasm-pack in seconds vs. minutes
      - name: install wasm-pack
        uses: jetli/wasm-pack-action@f98777369a49686b132a9e8f0fdd59837bf3c3fd
        with:
          version: v0.10.3

      - name: Build WASM package
        run: |
          cd client
          wasm-pack build --target web  --out-dir ../sites/usespiral/pkg

      - name: Hash all code files
        run: |
          date > hashes.txt
          for fname in pkg/client.js pkg/client_bg.wasm js/main.js js/pako.js
          do
            echo $fname "sha256 (base64)" >> hashes.txt
            cat sites/usespiral/$fname | openssl dgst -sha256 -binary | openssl base64 -A >> hashes.txt
            echo '\n' >> hashes.txt
          done
  
      - name: Upload intermediates
        uses: actions/upload-artifact@v3
        with:
          name: intermediates
          path: |
            hashes.txt
            sites/usespiral/pkg/client.js
            sites/usespiral/pkg/client_bg.wasm

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.9.0

      - name: Install Webpack
        run: npm install webpack@5.74.0 webpack-cli@4.10.0

      - name: Webpack all code into bundle
        run: |
          cd sites/usespiral
          webpack --config webpack.config.js
          
      - name: Upload client code bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: sites/usespiral/dist/bundle.js


  client-publish:
    name: Publish client code
    needs: client-build
    runs-on: ubuntu-latest

    steps:
      - name: Download bundle
        uses: actions/download-artifact@v3
        with:
          name: bundle
          
      - name: Generate bundle hash
        run: |
          date > hashes.txt
          echo "bundle.js sha256 (base64):" >> hashes.txt
          cat bundle.js | openssl dgst -sha256 -binary | openssl base64 -A >> hashes.txt

      - name: publish JS bundle
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bundle.js"
          tag: "latest"
          allowUpdates: true
          bodyFile: hashes.txt
